# Generated by Django 3.2.5 on 2021-07-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='dae_add',
            new_name='date_add',
        ),
    ]
