# Generated by Django 3.2.5 on 2021-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_dae_add_products_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bargain_bool',
            field=models.BooleanField(default=False, help_text='Торг'),
        ),
    ]
