# Generated by Django 3.2.5 on 2021-07-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_bargain_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='productsimage',
            name='image',
            field=models.ImageField(upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(related_name='products_id', to='shop.Products'),
        ),
    ]
